### ISSUE TITLE
mTLS fails to persist.

### ISSUE THREAD

**Issue by danktankk** [0xfurai/peekaping#19]
I’ve been trying to use mTLS with peekaping to monitor some internal services that require client certificates. I filled in the certificate, key, and ca fields within the UI with tested, valid data, but the monitor keeps failing with a “tls certificate required” error.  After checking the logs, it looks like the app isn’t actually using any of the mTLS values I provided and all the cert fields show up as empty in the request.

`DEBUG   executor/http.go:252    execute http cfg: &{Url:https://<target> Method:GET ... TlsCert: TlsKey: TlsCa:}`

`HTTP request failed: Commafeed, Get "https://sub.domain.com": remote error: tls: certificate required`

I have mtls terminating through traefik and do not use the included nginx block, but may try it for shits and giggles if it is believed to be user error.

Lastly, it seems like peekaping is either not saving the data from the UI, or just not passing it to the backend at all.  With respect to not saving data, I also noticed that when going back to edit any of the services, all the settings I used are gone except for the URL and the monitor type. Tthe user is ultimately left with no idea what was set, especially if some time goes by.  mTLS support was one of the reasons I was excited to try this out.  Any help is appreciated.  Thanks for your hard work!

**Comment by 0xfurai** [comment]
Thanks for reporting!
Fixed in 0.0.14

**Comment by 0xfurai** [comment]
@danktankk did you download latest version? 
now you have ability to set certificates

<img width="611" height="1224" alt="Image" src="https://github.com/user-attachments/assets/9fa525f2-697e-422c-bd10-07472eedc0ba" />

**Comment by danktankk** [comment]
> [@danktankk](https://github.com/danktankk) did you download latest version? now you have ability to set certificates

I can confirm this works for docker.  Nice work man.

https mTLS still doesnt want to work for me.  It also is requiring the ca cert and it isnt needed as the RP terminates client certs with the corresponding ca
